
version: '3.7'



services:
  fast-api:
    build: ./app
    container_name: test_con
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db_con
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oliver
    volumes:
      - db_volume:/var/lib/postgresql
volumes:
  db_volume:
